apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-1
  labels:
    jenkins: agent
spec:
  containers:
    - name: agent
      image: ubuntu:22.04
      command: ["sleep"]
      args: ["infinity"]
